controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\db\Query;
use yii\web\Controller;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ProductForm;
use app\models\Articles;
use app\models\ArticlesSearch;
use app\models\Categories;
use app\models\Products;
use app\models\ProductsSearch;
use app\models\Projects;
use app\models\Reviews;
use app\models\Price;
use app\models\ReviewsSearch;
use app\models\User;
use yii\web\BadRequestHttpException;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use app\widgets\ImagesHelper;

class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }
    
    public function beforeAction($event)
    {
        if ($this->action->id != 'admin')
            Yii::$app->assetManager->bundles['yii\bootstrap\BootstrapAsset'] = ['css' => []];
        return parent::beforeAction($event);
    }

    public function actionIndex()
    { 
        $this->layout = 'main_page';
        
        $meta = User::find()->select(['main_key', 'main_description'])->where(['status' => User::ROLE_ADMIN])->asArray()->one();
        Yii::$app->view->registerMetaTag(['name' => 'keywords', 'content' => $meta['main_key']]);
        Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => $meta['main_description']]);
        
        if (isset($_GET['cat']))
        {
            $category = Categories::find()->select('id')->where(['title' => $_GET['cat']])->asArray()->one();
            $cookies = Yii::$app->response->cookies;
            $cookies->add(new \yii\web\Cookie([
                'name' => 'category',
                'value' => $category['id']
            ]));
            $this->redirect(['site/products']);
        }
        if (Yii::$app->request->isAjax && isset($_POST['alias']))
        {
            $project = Articles::find()->where(['slug' => $_POST['alias']])->asArray()->one();
            $this->isModel($project);
            echo $project['text'];
            Yii::$app->end();
        }
        $tabs = Articles::find()->select(['text'])->where(['LIKE', 'slug', 'tab%', false])->asArray()->all();
        $services = Articles::find()->where(['slug' => 'nashi-uslugi'])->asArray()->one();
        $slider = Products::find()->select(['slug','title','image','price','currency','unit','action','popular','new'])
                                  ->where(['OR', 'action=1', 'popular=1', 'new=1'])->andWhere(['active' => 1])->asArray()->all();
        $reviewsModel = new ReviewsSearch;
        $dataProvider = $reviewsModel->search(Yii::$app->request->queryParams, Reviews::find()->select('name,text,image')->where(['active' => 1]));
        
        foreach($slider as $slide)
        {
           if (!empty($slide['image']))
           {
               $img = Json::decode($slide['image']);
               $images = new ImagesHelper();
               $slide['image'] = $images->render_asTag($img, 207, 207,true);
           }
           else
               $slide['image'] = '';    
               
           if ($slide['action'] == 1)
               $slider_all[1][] = $slide;
           if ($slide['popular'] == 1)
               $slider_all[2][] = $slide;
           if ($slide['new'] == 1)
               $slider_all[3][] = $slide;                     
        }
        $projects = Projects::find()->where(['active' => 1])->asArray()->all();
        
        return $this->render('index', [
                'tabs' => $tabs,
                'services' => $services,
                'slider' => $slider_all,
                'projects' => $projects,
                'reviews' => $dataProvider
            ]);
    }

    public function actionAdmin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['admin/site/index']);
        } else {
            return $this->renderAjax('login', [
                'model' => $model
            ]);
        }
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post())) {
            
            $admin = User::findOne(['status' => User::ROLE_ADMIN]);
            if (empty($admin) || empty($admin->email)) throw new BadRequestHttpException('Не задан E-mail администратора.');
            
            $model->contact($admin->email);
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model
            ]);
        }
    }

    public function actionNews()
    {
        $searchModel = new ArticlesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('blog', [
            'dataProvider' => $dataProvider
        ]);
    }
    
    public function actionArticle($id)
    {
        $model = Articles::find()->where(['slug' => $id])->asArray()->one();
        
        $this->isModel($model);
        
        return $this->render('article', [
            'model' => $model
        ]);
    }
    
    public function actionDostavkaIOplata()
    {
        $model = Articles::find()->where(['slug' => 'dostavka-i-oplata'])->asArray()->one();
        
        $this->isModel($model);
        
        return $this->render('page', [
            'model' => $model
        ]);
    }
    
    public function actionONas()
    {
        $model = Articles::find()->where(['slug' => 'o-nas'])->asArray()->one();
        
        $this->isModel($model);
        
        return $this->render('page', [
            'model' => $model
        ]);
    }
    
    public function actionProducts()
    {
        $where = '`active` = :active';
        $params = [':active' => 1];
        
        if (isset($_GET['category']) && !empty($_GET['category']))
        {
            $where .= ' AND `category_id` = :category';
            $params = array_merge($params,[':category' => $_GET['category']]);
            $cookies = Yii::$app->response->cookies;
            $cookies->add(new \yii\web\Cookie([
                'name' => 'category',
                'value' => $_GET['category']
            ]));
        }
        elseif(Yii::$app->request->cookies->has('category'))
        {
            $where .= ' AND `category_id` = :category';
            $params = array_merge($params,[':category' => Yii::$app->request->cookies->getValue('category')]);
        }
        foreach(Yii::$app->params['filters_id'] as $filter)
        {
            if (isset($_GET[$filter]) && !empty($_GET[$filter]))
            {
                $where .= ' AND `'.$filter.'_id` = :'.$filter;
                $params = array_merge($params,[':'.$filter => $_GET[$filter]]);
            }
        }
        
        $productsModel = new ProductsSearch;
        $dataProvider = $productsModel->search(Yii::$app->request->queryParams, Products::find()
                        ->select('slug,title,image,price,currency,unit,action,popular,new')
                        ->where($where)
                        ->orderBy(isset($_GET['price']) ? 'price '.$_GET['price'] : 'price ASC')
                        ->addParams($params));
        
        return $this->render('products', [
            'categories' => Categories::categoryList(),
            'products' => $dataProvider
        ]);
    }
    
    public function actionProduct($id = null, $category = null)
    {
        if (!is_null($category))
        {
            $cookies = Yii::$app->response->cookies;
            $cookies->add(new \yii\web\Cookie([
                'name' => 'category',
                'value' => $category
            ]));
            $this->redirect(['site/products']);
        }
        $model = Products::find()->where(['active' => 1, 'slug' => $id])->with('category')->asArray()->one();
        if (!empty($model['image']))
            $model['image'] = Json::decode($model['image']);
        if (!empty($model['file']))
            $model['file'] = Json::decode($model['file']);
        
        $this->isModel($model);
                        
        return $this->render('product', [
            'categories' => Categories::categoryList(),
            'model' => $model,
            'similar' => $this->productSlider($model['similar']),
            'related' => $this->productSlider($model['related'])
        ]);
    }
    
    public function actionProductRequest()
    {
        $model = new ProductForm();
        if (isset($_POST['type']) && $_POST['type'] == 'call')
             $model->scenario = 'call';
                
        if ($model->load(Yii::$app->request->post())) {
            
            $admin = User::findOne(['status' => User::ROLE_ADMIN]);
            if (empty($admin) || empty($admin->email)) throw new BadRequestHttpException('Не задан E-mail администратора.');
            
            $model->contact($admin->email);
            Yii::$app->session->setFlash('productFormSubmitted');

            $this->redirect(Yii::$app->request->referrer);
        }
        return $this->renderAjax('_popup', [
            'model' => $model
        ]);
    }
    
    private function productSlider($param)
    {
        if (!empty($param))
        {
            $result = Products::find()->select(['slug','title','image','price','currency','unit','action','popular','new'])
                    ->where('`active` = 1 AND id IN('.$param.')')->asArray()->all();
            foreach($result as $key => $slide)
            {
                if (!empty($slide['image']))
                {
                    $img = Json::decode($slide['image']);
                    $images = new ImagesHelper(); 
                    $result[$key]['image'] = $images->render_asTag($img, 207, 207,true);

views/site/_popup.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
 
$form = ActiveForm::begin(['id' => 'call-form', 'class' => 'form']);
echo $form->field($model, 'name')->textInput(['class' => 'input', 'placeholder' => 'Ваше Имя'])->label(false);
echo $form->field($model, 'email')->textInput(['class' => 'input', 'placeholder' => 'Email'])->label(false);
echo $form->field($model, 'phone')->textInput()->label(false)->widget(\yii\widgets\MaskedInput::className(), [
         'options' => [
             'class' => 'input',
             'placeholder' => 'Телефон'
         ],
        'mask' => '999-999-9999'
]);
if ($model->scenario == 'call')
    echo $form->field($model, 'time')->textInput(['class' => 'input', 'placeholder' => 'Удобное время для звонка'])->label(false);
echo $form->field($model, 'product')->hiddenInput()->label(false);
?>
<div class="form-group">
<?= Html::submitButton('Отправить', ['class' => 'submit']); ?>
</div>
<?php ActiveForm::end(); ?>

views/site/_product.php
<?php 
use yii\helpers\Url;
use app\widgets\ImagesHelper;
?>
<a class="pad" href="<?= Url::to(['/site/product', 'id' => $model->slug]) ?>" data-pjax="0">
    <div class="item<?=Yii::$app->controller->action->id == 'product' ? 2 : 3?>">
	    <div class="product_a">
		    <div class="in_product
            <?php 
            if ($model->action == 1)
                echo ' action';
            elseif ($model->popular == 1)
                echo ' popular';
            elseif ($model->new == 1)
                echo ' new';
            ?>"></div> 
            <div class="product_a_img specials" <?php if (!empty($model->image)): ?>style="background-image: url(<?php $images = new ImagesHelper(); echo $images->render_asTag($model->image, 207, 207,true)?>);"<?php endif; ?>></div>
			<div class="product_a_name2">
				<?=$model->title?>
			</div>
			<div class="product_a_price">
				<div class="cena_prod"><?=Yii::$app->formatter->asCurrency($model->price, $model->currency)?></div> <span class="cena_prod2"><?=Yii::$app->params['units'][$model->unit]?></span>
			</div>
		</div>
	</div>
</a>

views/site/_review.php
<div class="od_right" style="background-image: url('/images/reviews/<?=$model->image?>');">
	<div class="od_left_od2"><?=$model->name?></div>
	<div class="od_left_te2"><?=$model->text?></div>
</div>

views/site/_slider.php
<?php
use yii\helpers\Url;	
?>
<div class="owl-carousel">
    <?php foreach($data as $slide): ?>
    <div class="item">
		<a class="pad" href="<?=Url::to(['/site/product', 'id' => $slide['slug']])?>">
            <div class="product_a">
                <div class="in_product
                <?php 
                if ($slide['action'] == 1)
                    echo ' action';
                elseif ($slide['popular'] == 1)
                    echo ' popular';
                elseif ($slide['new'] == 1)
                    echo ' new';
                ?>"></div> 
				<div class="product_a_img specials" <?php if (!empty($slide['image'])): ?>style="background-image: url(<?=$slide['image']?>);"<?php endif; ?>></div>
				<div class="prode"></div>
				<div class="product_a_name" style="color: #000;">
					<?=$slide['title']?>
				</div>
				<div class="product_a_price">
				<div><?=Yii::$app->formatter->asCurrency($slide['price'], $slide['currency'])?></div> <?=Yii::$app->params['units'][$slide['unit']]?>
				</div>
            </div>    
        </a>	
	</div>
    <?php endforeach; ?>
</div>

views/site/article.php
<?php
$this->title = $model['title'];

$this->registerMetaTag(['name' => 'keywords', 'content' => $model['metakey']]);
$this->registerMetaTag(['name' => 'description', 'content' => $model['metadiscription']]);
?>
<div class="name_page"><?= $this->title ?></div>
<?php
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['site/news']];
$this->params['breadcrumbs'][] = $this->title;	
?>
<div class="main_center"><?= $model['text'] ?></div>

views/site/blog.php
<?php
use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
$this->title = 'Новости';
$this->registerMetaTag(['name' => 'keywords', 'content' => '']);
$this->registerMetaTag(['name' => 'description', 'content' => '']);
?>
<div class="name_page"><?= Html::encode($this->title) ?></div>
    <div class="main_center">
    <?php Pjax::begin(['options' => ['id'=>'news']]);
    echo ListView::widget([
            'dataProvider' => $dataProvider,
                'itemView' => '_item',
                'pager' => [
                    'nextPageLabel' => false,
                    'prevPageLabel' => false
                ],
                'layout' => '{items}<div class="clearfix"></div><div class="news_pager">{pager}</div>'
        ]);
        Pjax::end();                    
    ?>
    </div>

views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Контакты';
?>
    <div class="name_page"><?= Html::encode($this->title) ?></div>
    
    <div class="main_center">
				<div class="cont_info">
					<div class="cont_left_line"></div>
					<div class="cont_right_line"></div>
					<div class="cont_center_title">Свяжитесь с нами уже сегодня!</div>
					<!--<div class="cont_text">
						Альтернативное объяснение предполагает, что формация деформирует оз, что в конце концов приведет к полному разрушению хребта под действием собственного веса. Замерзание, с зачастую загипсованными породами, стягивает ийолит-уртит. Литосфера, как теперь известно, старица своеобразна. 
					</div>-->
				</div>
				<div class="cont_main_form">
					<div class="cont_form_left">
						<div class="cont_form_adres">
							Адрес: г. Киев, ул. Кирилловская<br> (Фрунзе), 102
						</div>
						<div class="cont_form_tel">
							044-465-70-88 <br> 067-158-41-28
						</div>
						<div class="cont_form_mail">
							info@ilaya-west.com
						</div>
					</div>
					<div class="cont_form_right">
            <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

             <div class="senks">Спасибо, что связались с нами. Мы ответим Вам как можно скорее.</div>

            <?php else: ?>
			<?php $form = ActiveForm::begin(['id' => 'contact-form', 'class' => 'form']); ?>
                <?= $form->field($model, 'name')->textInput(['class' => 'input', 'size' => 40, 'placeholder' => 'Ваше Имя'])->label(false) ?>
                <?= $form->field($model, 'email')->textInput(['class' => 'input', 'size' => 40, 'placeholder' => 'Email'])->label(false) ?>
                <?= $form->field($model, 'body')->textArea(['class' => 'input','rows' => 3, 'cols' => 40, 'placeholder' => 'Сообщение'])->label(false) ?>
                <div class="form-group">
                    <?= Html::submitButton('ОТПРАВИТЬ', ['class' => 'submit', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
            <?php endif; ?>
					</div>
				</div>
			</div>
        <div class="karta">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2538.91763917256!2d30.479712793112718!3d50.479876973224705!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4cde70140c059%3A0x7dc2b61af3da1f46!2z0LLRg9C7LiDQmtC40YDQuNC70ZbQstGB0YzQutCwLCAxMDIsINCa0LjRl9Cy!5e0!3m2!1suk!2sua!4v1434624820633" style="width:100%" height="500" frameborder="0" style="border:0"></iframe>
		</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="name_page"><?= Html::encode($this->title) ?></div>

<div class="main_center">
    <?= nl2br(Html::encode($message)) ?>
</div>

views/site/index.php
<?php
use yii\widgets\ListView;
use yii\widgets\Pjax;
use yii\helpers\Url;

/* @var $this yii\web\View */
$this->title = Yii::$app->name;

if (!empty($slider)){
    $this->registerJsFile(YII_DEBUG ? 'js/owl.carousel.js' : 'js/owl.carousel.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
    $this->registerCssFile(YII_DEBUG ? 'css/carousel.css' : 'css/carousel.min.css');
}
if (!empty($projects)){
    $this->registerJsFile('js/jquery.bxslider.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
    $this->registerCssFile(YII_DEBUG ? 'css/jquery.bxslider.css' : 'css/jquery.bxslider.min.css');   
}
$this->registerJsFile(YII_DEBUG ? 'js/scripts.js' : 'js/scripts.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
?>
<section class="t_sect">
			<div class="main_center">
				<div class="left_t_blok">
					<div class="left_t_title">
						Выберите интересующий Вас вид черепицы
					</div>
					<div id="wrapper" class="tab1">
                                                
						<?php $i = 1; foreach($tabs as $key => $tab): ?>
                        <a class="tab<?=$i?>">
						<span class="img_ce ce<?=$i?>">
							
						</span></a>
                        <div class="tab<?=$i?> left_t_text">
							<?=$tabs[$key]['text']?> 
						</div>                        
                        <?php $i++; endforeach; ?>
                                                
					</div>
					<div class="left_t_home">
						
					</div>
				</div>
				<div class="right_t_blok">
		
				</div>
		
			</div>
		</section>
          
        <?php if (!empty($slider)): ?>
        <section class="cvcv">
			<div class="main_center">
				<div id="wrapper1" class="tab11">
					<a class="tab11">Акции</a>
					<a class="tab22">Популярные товары</a>
					<a class="tab33">Новинки</a>
							
					<?php foreach($slider as $key => $slides): ?>
                    <span class="tab<?=$key.$key?>">
                    <div class="owl-carousel">
                     <?php foreach($slides as $slide): ?>
                        <div class="item">
							<a class="pad" href="<?=Url::to(['/site/product', 'id' => $slide['slug']])?>">
                                <div class="product_a">
									<div class="product_a_img" <?php if (!empty($slide['image'])): ?>style="background-image: url(<?=$slide['image']?>);"<?php endif; ?>>
									</div>
									
									<div class="prode">
									</div>
									<div class="product_a_name">
										<?=$slide['title']?>
									</div>
									<div class="product_a_price">
										<div><?=Yii::$app->formatter->asCurrency($slide['price'], $slide['currency'])?></div> <?=Yii::$app->params['units'][$slide['unit']]?>
									</div>
                                </div>    
                             </a>	
						</div>
                    <?php endforeach; ?>
                    </div>
                    </span>
                    <?php endforeach; ?>
				    
			    </div>
            </div>
		</section>
        <?php endif; ?>
        
        <?=$services['text']?>
        
        <?php if (!empty($projects)): ?>
        <div id="projects" class="name_page_bl2">
			<span>Наши Проекты</span>
		</div>
		
		<div class="slider4">
        
        <?php foreach($projects as $project): ?>
            <div class="slide" style="background-image: url(/images/projects/<?=$project['image']?>);">
                <div class="top_prod">
                    <span class="s_ti"><?=$project['title']?></span>
                    <span class="s_ti2"><?=$project['description']?></span>
                    <span class="s_ti3">
                        <a href="#popup" onclick="js:popup_content('<?=$project['alias']?>')" class="btn">Подробнее</a>
                    </span>
                </div>
            </div>
        <?php endforeach; ?>
			
		</div>
        <?php endif; ?>
        
        <a href="#projects" class="overlay" id="popup"></a>
		<div id="popupForm">
		    <a href="#projects" class="close">X</a>
			<div class="main_center">
			    <div class="name_page33">Наши Проекты</div>
                <div class="main_nas">
                    <div id="popup_content"></div>
                </div>
			</div>		
		</div>
        
        <div class="od">
			<div class="main_center">
				<div class="od_left">
					<div class="od_left_od">ОТЗЫВЫ</div>
					<div class="od_left_te">Отзывы наших<br/> клиентов</div>
					
				</div>
                <?php Pjax::begin(['options' => ['id'=>'reviews']]);
                    echo ListView::widget([
                        'dataProvider' => $reviews,
                        'itemView' => '_review',
                        'pager' => [
                            'nextPageLabel' => false,
                            'prevPageLabel' => false
                         ],
                        'layout' => '{items}<div class="clear"></div><div class="rewiews_pager">{pager}</div>'
                    ]);
                    Pjax::end();                    
                ?>
			</div>
				<div class="clear"></div>
		</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Вход';

$this->registerJs("jQuery('#modal').modal('show');$('#modal').on('hidden.bs.modal', function () {location.href='".Yii::$app->homeUrl."'})");
?>
<?php
Modal::begin([
    'header' => '&nbsp;',
    'id' => 'modal',
    'size' => 'modal-sm'
]); ?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form'
    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe')->checkbox() ?>

    <div class="form-group">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>
       
<?php Modal::end(); ?>

views/site/product.php
<?php
use yii\helpers\Url;
use himiklab\colorbox\Colorbox;
use app\widgets\ImagesHelper;

$this->title = $model['title'];
$this->params['breadcrumbs'][] = ['label' => 'Продукция', 'url' => ['site/products']];
$this->params['breadcrumbs'][] = ['label' => $model['category']['title'], 'url' => ['site/products']];
$this->params['breadcrumbs'][] = $this->title;

if (!empty($similar)){
    $this->registerJsFile('/js/owl.carousel.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
    $this->registerCssFile('/css/carousel.css');
    $this->registerJs("
        $('.owl-carousel').owlCarousel({
	loop:true,
	margin:10,
	nav:true,
    singleItem:true,    
	responsive:{
		320:{
			items:1
		},
        360:{
			items:2
		},
		600:{
			items:3
		},
		1000:{
			items:4
		}
	}
})", \yii\web\View::POS_END);
}
$this->registerJs("
function popup_content(type){
    $.ajax({
       type: 'POST',
       url: '".Url::to(['/site/product-request'])."',
       data: {'type': type},
       success: function(data) {
           $('.name_page33').text(type == 'call' ? 'Заказать обратный звонок' : 'Уточнить скидку');
           $('#popup_content').html(data);
           $('#productform-product').val($('.active').text());
       }
    });
}
", \yii\web\View::POS_END);
?>
<div class="name_page">Продукция</div>

<?php if (Yii::$app->session->hasFlash('productFormSubmitted')): ?>
<div class="senks">Спасибо, что связались с нами. Мы ответим Вам как можно скорее.</div>
<?php endif; ?>

<div class="main_center">
				<div class="main_prod">
					<div class="left_prod">
						<?php foreach($categories as $key => $category): ?>     
                        <div class="left_bar">
							<a href="<?=Url::to(['site/product', 'category' => $key])?>"><?=$category?></a>
						</div>       
                        <?php endforeach; ?>
					</div>
					<div class="right_prod">
                        <div class="prod_images">
                            <div class="in_product
                            <?php 
                            if ($model['action'] == 1)
                                echo ' action';
                            elseif ($model['popular'] == 1)
                                echo ' popular';
                            elseif ($model['new'] == 1)
                                echo ' new';
                            ?>"></div>                       
                            <div class="img_prod" <?php if (!empty($model['image'])): ?>style="background-image: url('/images/products/<?=$model['image'][0]?>');"<?php endif; ?>></div>
                            <div class="clear"></div>
        <?php 
            $images = new ImagesHelper();
            
            Colorbox::widget([
                'targets' => [
                    '.colorbox' => [
                        'maxWidth' => 800,
                        'maxHeight' => 600,
                        'opacity' => 0.7
                    ],
                ],
                'coreStyle' => 1
            ]);
            
            if (!empty($model['image']))
            {
                foreach($model['image'] as $photo) : ?>
                    <a rel="gallery" class="colorbox" href="/images/products/<?= $photo ?>">
                        <div style="padding:1px;border:0" class="thumbnail">
                            <?= $images->render_asDiv($photo, 70, 70, true) ?>
                        </div>
                    </a>
                <?php endforeach;
            }
        ?>
                        </div>
						<div class="news_title22"><?=$model['title']?></div>
                        <div class="cena"><span class="cena_prod"><?=Yii::$app->formatter->asCurrency($model['price'], $model['currency'])?></span> <span class="cena_prod2"><?=Yii::$app->params['units'][$model['unit']]?></span></div>
                        <a href="#popup" onclick="js:popup_content('clarify')" class="botton product_btn" style="background-color: #94C359;">Уточнить скидку</a>
                        <a href="#popup" onclick="js:popup_content('call')" class="botton product_btn">Заказать обратный звонок</a>
        <a href="#product" class="overlay" id="popup"></a>
		<div id="popupForm">
		    <a href="#product" class="close">X</a>
			<div class="main_center">
			    <div class="name_page33"></div>
                <div class="main_nas">
                    <div id="popup_content"></div>
                </div>
			</div>		
		</div>
						<div class="text_prod"><?=$model['description']?></div>
                        <div class="clear"></div>
                        <br /><hr />
						<div class="news_title22"><?=$model['title']?></div>
                        <?php if (!empty($model['file'])): ?>
                        <?php foreach($model['file'] as $one): ?>
						<a download="" href="<?=Yii::getAlias('@web/files/').$one?>">
                            <div class="dok">Техническая Документация</div>
                        </a>
                        <?php endforeach; ?>
                        <?php endif; ?>
					</div>
				</div>
				<div class="clear"></div>
			</div>
<?php if (!empty($similar) || !empty($related)): ?>
<div class="name_page_bl"><span>Похожие товары</span></div>

    <div class="main_center">
	    <?php if (!empty($similar))
            echo $this->render('_slider', ['data' => $similar]); 
        ?>
        <div class="clear"></div>
                
        <?php if (!empty($related)): ?>
        
		<div class="left_t_title mar">
			С этим тваром также покупают
		</div>
		<div class="p_tov">	
			<?= $this->render('_slider', ['data' => $related]); ?>
			<div class="clear"></div>
		</div>
        
    <?php endif; ?>
	</div>
<?php endif; ?>